import type {JsonValue,Scope,DocumentSnapshot,DiagnosticsResult,LanguageFeature,LanguageRequest,LanguageResult,LanguageProvider} from './index.mjs';
import type {TrustedProcessDefinition} from './tool-streams-node.mjs';
export const LSP_LIMITS:Readonly<{messageBytes:number;headerBytes:number;sessionBytes:number;messages:number;pendingRequests:number;queuedWrites:number;timeoutMs:number;documents:number;documentBytes:number;stderrBytes:number}>;
export interface LspCapabilityMatrix {readonly schemaVersion:1;readonly protocol:'3.17';readonly transport:'stdio';readonly positionEncoding:'utf-16';readonly features:readonly {readonly sdkFeature:LanguageFeature;readonly method:string;readonly supported:boolean;readonly reason:'advertised'|'not-advertised'}[];readonly unsupported:readonly string[];}
export interface LspFrameDecoder {push(input:Uint8Array):readonly JsonValue[];finish():void;inspect():Readonly<{bufferedBytes:number;totalBytes:number;messages:number;failed:boolean}>;}
export interface LspInspection {readonly state:string;readonly generation:number;readonly documents:number;readonly requests:number;readonly diagnostics:number;readonly unversionedDropped:number;readonly staleDropped:number;readonly rejectedNotifications:number;readonly ignoredNotifications:number;readonly transport:Readonly<Record<string,JsonValue>>;readonly process:{readonly pid:number|null;readonly closed:boolean};}
export interface LspCloseReceipt {readonly schemaVersion:1;readonly graceful:boolean;readonly reason:string|null;readonly ownedProcessClosed:boolean;readonly pendingRequests:number;}
export interface LspBridge {capabilities():LspCapabilityMatrix;inspect():LspInspection;syncDocument(snapshot:DocumentSnapshot):Promise<void>;closeDocument(uri:string):Promise<void>;request<K extends LanguageFeature>(request:LanguageRequest<K>,options?:{readonly signal?:AbortSignal}):Promise<LanguageResult<K>>;provider<K extends LanguageFeature>(kind:K):LanguageProvider<K>;close():Promise<LspCloseReceipt>;}
export function encodeLspMessage(message:JsonValue):Uint8Array;
export function createLspFrameDecoder():LspFrameDecoder;
export function lspCapabilityMatrix(capabilities:JsonValue):LspCapabilityMatrix;
export function parseLspCapabilityMatrix(input:unknown):LspCapabilityMatrix;
export function createLspBridge(options:{readonly process:TrustedProcessDefinition;readonly workspaceRoot:string;readonly scope:Scope;readonly authorize:(context:{readonly operation:'start'|'read'|'edit'|'diagnostics';readonly scope:Scope;readonly path:string|null;readonly serverId:string;readonly serverVersion:string})=>boolean|Promise<boolean>;readonly onDiagnostics?:(result:DiagnosticsResult)=>void|Promise<void>;readonly readDocument?:(path:string,options:{readonly signal:AbortSignal})=>DocumentSnapshot|Promise<DocumentSnapshot>;readonly configuration?:JsonValue;readonly initializationOptions?:JsonValue;readonly expectedServerName?:string;readonly requestTimeoutMs?:number;readonly signal?:AbortSignal;readonly secrets?:readonly string[]}):Promise<LspBridge>;
