export interface UpstreamSource {readonly url:string;readonly version:string;readonly sha256:string;}
export interface UpstreamFetch {readonly schemaVersion:1;readonly source:UpstreamSource;readonly observedAt:number;readonly status:'verified'|'unavailable'|'offline'|'unverified'|'digest-mismatch';readonly actualSha256:string|null;readonly bytes:number;readonly redirects:readonly string[];readonly reason:string|null;readonly artifact:Uint8Array|null;}
export interface UpstreamManifest {readonly schemaVersion:1;readonly name:string;readonly version:string;readonly revision:string;readonly api:readonly string[];readonly license:{readonly name:string;readonly text:string;readonly notice:string;readonly redistributable:boolean};readonly files:readonly {readonly path:string;readonly sha256:string}[];}
export interface UpstreamSnapshot {readonly schemaVersion:1;readonly source:UpstreamSource;readonly observedAt:number;readonly manifest:UpstreamManifest;readonly manifestSha256:string;}
export interface UpstreamCandidate {readonly schemaVersion:1;readonly current:UpstreamSnapshot;readonly candidate:UpstreamSnapshot;readonly tagChanged:boolean;readonly api:{readonly added:readonly string[];readonly removed:readonly string[];readonly missingRequired:readonly string[]};readonly files:{readonly added:readonly string[];readonly removed:readonly string[];readonly changed:readonly string[]};readonly licenseChanged:boolean;readonly redistributable:boolean;readonly compatibility:'supported'|'unsupported'|'unverified';readonly functional:{readonly state:'passed'|'failed'|'unverified';readonly detail:string};readonly patch:{readonly expectedSourceSha256:string;readonly replacementSource:UpstreamSource};readonly reviewRequired:true;readonly automaticActions:readonly never[];readonly sha256:string;}
export function fetchUpstreamArtifact(options:{readonly source:UpstreamSource;readonly allowedUrls:readonly string[];readonly enabled:true;readonly offline:boolean;readonly maxBytes:number;readonly timeoutMs:number;readonly allowLoopback?:boolean;readonly signal?:AbortSignal}):Promise<UpstreamFetch>;
export function createUpstreamManifest(value:Omit<UpstreamManifest,'schemaVersion'>):UpstreamManifest;
export function inspectUpstreamManifest(bytes:Uint8Array,source:UpstreamSource,observedAt:number):UpstreamSnapshot;
export function createUpstreamCandidate(options:{readonly current:UpstreamSnapshot;readonly candidate:UpstreamSnapshot;readonly support:{readonly versions:readonly string[];readonly requiredApi:readonly string[]};readonly check?:(candidate:UpstreamSnapshot,context:{readonly signal?:AbortSignal})=>Promise<{passed:boolean;detail:string}>|{passed:boolean;detail:string};readonly signal?:AbortSignal}):Promise<UpstreamCandidate>;
