import type {JsonValue} from './index.mjs';
import type {WorkflowScope} from './workflows.mjs';
import type {OwnedStoreCleanup} from './workflows-node.mjs';
export const WORKFLOW_CACHE_LIMITS:Readonly<{entries:number;bytes:number;valueBytes:number;files:number;fileBytes:number;inputBytes:number;ttlMs:number;concurrentFills:number;fillTimeoutMs:number}>;
export interface WorkflowCachePolicy {readonly optIn:boolean;readonly deterministic:boolean;readonly declaredInputsComplete:boolean;readonly secretDependent:boolean;}
export interface WorkflowFingerprintInput {readonly scope:WorkflowScope;readonly commandId:string;readonly pluginSha256:string;readonly toolSha256:string|null;readonly schema:JsonValue;readonly settings:JsonValue;readonly environment:{readonly declared:readonly string[];readonly values:Readonly<Record<string,string>>};readonly input:JsonValue;readonly files:readonly {readonly path:string;readonly bytes:Uint8Array}[];readonly grants:readonly string[];readonly policy:WorkflowCachePolicy;}
export interface WorkflowFingerprint {readonly schemaVersion:1;readonly key:string;readonly eligible:boolean;readonly reasons:readonly string[];readonly descriptor:{readonly schemaVersion:1;readonly sdkVersion:string;readonly scope:WorkflowScope;readonly commandId:string;readonly pluginSha256:string;readonly toolSha256:string|null;readonly schemaSha256:string;readonly settingsSha256:string;readonly inputSha256:string;readonly environmentSha256:string;readonly files:readonly {readonly path:string;readonly byteLength:number;readonly sha256:string}[];readonly grants:readonly string[];readonly policy:WorkflowCachePolicy};}
export interface WorkflowCacheEntry {readonly schemaVersion:1;readonly key:string;readonly scope:WorkflowScope;readonly grants:readonly string[];readonly value:JsonValue;readonly valueSha256:string;readonly createdAt:number;readonly expiresAt:number;readonly accessedAt:number;readonly byteLength:number;}
export interface WorkflowCacheStore {get(key:string):Promise<WorkflowCacheEntry|null>;set(key:string,value:WorkflowCacheEntry):Promise<void>;list():Promise<readonly string[]>;remove(key:string):Promise<boolean>;cleanup?():Promise<OwnedStoreCleanup>;}
export interface WorkflowCacheResult {readonly state:'hit'|'miss'|'shared'|'bypass';readonly reason:string;readonly value:JsonValue;}
export interface WorkflowCache {inspect():Readonly<{hits:number;misses:number;bypasses:number;shared:number;evicted:number;corrupt:number;writes:number;writeFailures:number;pendingFills:number;unsettled:number;closed:boolean}>;run(input:WorkflowFingerprint,options:{readonly compute:(context:{readonly signal:AbortSignal})=>JsonValue|Promise<JsonValue>;readonly signal?:AbortSignal}):Promise<WorkflowCacheResult>;cleanup():Promise<{readonly removed:readonly string[];readonly recovery:OwnedStoreCleanup}>;close():Promise<void>;}
export function fingerprintWorkflowInputs(input:WorkflowFingerprintInput):WorkflowFingerprint;
export function parseWorkflowFingerprint(input:unknown):WorkflowFingerprint;
export function parseWorkflowCacheEntry(input:unknown):WorkflowCacheEntry;
export function createMemoryWorkflowCacheStore():WorkflowCacheStore;
export function createWorkflowCache(options:{readonly store?:WorkflowCacheStore;readonly authorize:(context:{readonly scope:WorkflowScope;readonly commandId:string;readonly grants:readonly string[];readonly key:string;readonly phase:'lookup'|'fill'|'after-fill'|'hit'|'return'})=>boolean|Promise<boolean>;readonly now?:()=>number;readonly ttlMs?:number;readonly maxEntries?:number;readonly maxBytes?:number;readonly fillTimeoutMs?:number}):WorkflowCache;
